<html>
  <head>
    <meta charset="utf-8" />
    <title>Projeto 3</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  </head>

  <body>
    <div class="container">
      <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
          <div class="card-body">

            <div class="row">
              <div class="col mb-4" align="center">
                <h2>Faça o login!</h2>
              </div>
            </div>

            <div class="row">
              <div class="col">
                
                <form action="/projeto_3/logar.php" method="post">
                  <div class="form-group">
                    <input required name="email" type="text" class="form-control" placeholder="E-mail">
                  </div>

                  <div class="form-group">
                    <input required name="senha" type="password" class="form-control" placeholder="Senha">
                  </div>
                  
                  <button type="submit" class="btn btn-primary btn-block">Logar</button>
                </form>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </body>

</html>