<html>
  <head>
    <meta charset="utf-8" />
    <title>Projeto 2</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  </head>

  <body>
    <div class="container">
      <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
          <div class="card-body">

            <div class="row">
              <div class="col" align="center">
                <h2>Login realizado com sucesso! Seja bem-vindo(a) de volta!</h2>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

</html>